-- Backlogger Supabase sync schema.
-- The application never writes these tables directly. Authenticated clients use
-- the narrowly scoped functions at the end of this migration.

create table public.sync_notebooks (
  notebook_id text primary key,
  owner_id uuid not null references auth.users (id) on delete cascade,
  manifest jsonb not null,
  manifest_version bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sync_notebooks_notebook_id_not_blank check (btrim(notebook_id) <> ''),
  constraint sync_notebooks_owner_id_key unique (owner_id),
  constraint sync_notebooks_manifest_version_positive check (manifest_version > 0),
  constraint sync_notebooks_manifest_valid check (
    jsonb_typeof(manifest) = 'object'
    and manifest ->> 'type' = 'manifest'
    and jsonb_typeof(manifest -> 'protocolVersion') = 'number'
    and manifest ->> 'protocolVersion' = '1'
    and manifest ->> 'notebookId' = notebook_id
  )
);

create table public.sync_snapshots (
  notebook_id text not null references public.sync_notebooks (notebook_id) on delete cascade,
  snapshot_id text not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  primary key (notebook_id, snapshot_id),
  constraint sync_snapshots_notebook_id_not_blank check (btrim(notebook_id) <> ''),
  constraint sync_snapshots_snapshot_id_not_blank check (btrim(snapshot_id) <> ''),
  constraint sync_snapshots_payload_valid check (
    jsonb_typeof(payload) = 'object'
    and jsonb_typeof(payload -> 'protocolVersion') = 'number'
    and payload ->> 'protocolVersion' = '1'
    and payload ->> 'type' in ('snapshot', 'checkpoint')
    and payload ->> 'notebookId' = notebook_id
    and payload ->> 'snapshotId' = snapshot_id
  )
);

create index sync_snapshots_notebook_id_idx
  on public.sync_snapshots (notebook_id);

alter table public.sync_notebooks enable row level security;
alter table public.sync_snapshots enable row level security;

create policy sync_notebooks_select_own
  on public.sync_notebooks
  for select
  to authenticated
  using (owner_id = (select auth.uid()));

create policy sync_snapshots_select_own
  on public.sync_snapshots
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.sync_notebooks as n
      where n.notebook_id = sync_snapshots.notebook_id
        and n.owner_id = (select auth.uid())
    )
  );

-- Do not rely on the default grants generated by a fresh Supabase project.
-- Reads are allowed through RLS; all writes go through the functions below.
revoke all on table public.sync_notebooks from public, anon, authenticated;
revoke all on table public.sync_snapshots from public, anon, authenticated;
grant select on table public.sync_notebooks, public.sync_snapshots to anon, authenticated;

create or replace function public.initialize_sync_notebook(
  p_notebook_id text,
  p_snapshot_id text,
  p_snapshot jsonb,
  p_manifest jsonb
)
returns table (manifest jsonb, manifest_version bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner_id uuid := auth.uid();
begin
  if v_owner_id is null then
    raise exception 'authenticated user required' using errcode = '42501';
  end if;

  if p_notebook_id is null or btrim(p_notebook_id) = ''
    or p_snapshot_id is null or btrim(p_snapshot_id) = '' then
    raise exception 'notebook and snapshot ids must be nonblank' using errcode = '22023';
  end if;

  if jsonb_typeof(p_snapshot) is distinct from 'object'
    or jsonb_typeof(p_snapshot -> 'protocolVersion') is distinct from 'number'
    or p_snapshot ->> 'protocolVersion' is distinct from '1'
    or p_snapshot ->> 'type' is distinct from 'checkpoint'
    or jsonb_typeof(p_snapshot -> 'checkpointVersion') is distinct from 'number'
    or p_snapshot ->> 'notebookId' is distinct from p_notebook_id
    or p_snapshot ->> 'snapshotId' is distinct from p_snapshot_id
    or p_snapshot ->> 'checkpointVersion' is distinct from '1' then
    raise exception 'initial snapshot is not a protocol v1 checkpoint' using errcode = '22023';
  end if;

  if jsonb_typeof(p_manifest) is distinct from 'object'
    or p_manifest ->> 'type' is distinct from 'manifest'
    or jsonb_typeof(p_manifest -> 'protocolVersion') is distinct from 'number'
    or p_manifest ->> 'protocolVersion' is distinct from '1'
    or p_manifest ->> 'notebookId' is distinct from p_notebook_id
    or jsonb_typeof(p_manifest -> 'headSnapshotIds') is distinct from 'array'
    or jsonb_array_length(p_manifest -> 'headSnapshotIds') <> 1
    or (p_manifest -> 'headSnapshotIds' ->> 0) is distinct from p_snapshot_id
    or jsonb_typeof(p_manifest -> 'prunedSnapshotIds') is distinct from 'array'
    or jsonb_array_length(p_manifest -> 'prunedSnapshotIds') <> 0 then
    raise exception 'initial manifest is not a single-checkpoint manifest' using errcode = '22023';
  end if;

  insert into public.sync_notebooks (notebook_id, owner_id, manifest, manifest_version)
  values (p_notebook_id, v_owner_id, p_manifest, 1);

  insert into public.sync_snapshots (notebook_id, snapshot_id, payload)
  values (p_notebook_id, p_snapshot_id, p_snapshot);

  return query
    select n.manifest, n.manifest_version
    from public.sync_notebooks as n
    where n.notebook_id = p_notebook_id
      and n.owner_id = v_owner_id;
exception
  when unique_violation then
    raise exception 'notebook already exists' using errcode = '23505';
end;
$$;

create or replace function public.create_sync_snapshot(
  p_notebook_id text,
  p_snapshot_id text,
  p_payload jsonb
)
returns table (status text, payload jsonb)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner_id uuid := auth.uid();
  v_existing jsonb;
begin
  if v_owner_id is null then
    raise exception 'authenticated user required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.sync_notebooks as n
    where n.notebook_id = p_notebook_id
      and n.owner_id = v_owner_id
  ) then
    raise exception 'notebook is not owned by the authenticated user' using errcode = '42501';
  end if;

  if p_snapshot_id is null or btrim(p_snapshot_id) = ''
    or jsonb_typeof(p_payload) is distinct from 'object'
    or jsonb_typeof(p_payload -> 'protocolVersion') is distinct from 'number'
    or p_payload ->> 'protocolVersion' is distinct from '1'
    or p_payload ->> 'type' not in ('snapshot', 'checkpoint')
    or p_payload ->> 'notebookId' is distinct from p_notebook_id
    or p_payload ->> 'snapshotId' is distinct from p_snapshot_id then
    raise exception 'snapshot payload is not a valid protocol v1 snapshot' using errcode = '22023';
  end if;

  insert into public.sync_snapshots (notebook_id, snapshot_id, payload)
  values (p_notebook_id, p_snapshot_id, p_payload)
  on conflict (notebook_id, snapshot_id) do nothing;

  if found then
    return query select 'created'::text, p_payload;
    return;
  end if;

  select s.payload
    into v_existing
  from public.sync_snapshots as s
  where s.notebook_id = p_notebook_id
    and s.snapshot_id = p_snapshot_id;

  if v_existing is distinct from p_payload then
    raise exception 'snapshot id already contains different immutable content'
      using errcode = 'P0001';
  end if;

  return query select 'already-identical'::text, v_existing;
end;
$$;

create or replace function public.compare_and_swap_sync_manifest(
  p_notebook_id text,
  p_expected_manifest_version bigint,
  p_manifest jsonb
)
returns table (applied boolean, manifest jsonb, manifest_version bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner_id uuid := auth.uid();
  v_manifest jsonb;
  v_manifest_version bigint;
begin
  if v_owner_id is null then
    raise exception 'authenticated user required' using errcode = '42501';
  end if;

  if p_expected_manifest_version is null or p_expected_manifest_version < 1
    or jsonb_typeof(p_manifest) is distinct from 'object'
    or p_manifest ->> 'type' is distinct from 'manifest'
    or jsonb_typeof(p_manifest -> 'protocolVersion') is distinct from 'number'
    or p_manifest ->> 'protocolVersion' is distinct from '1'
    or p_manifest ->> 'notebookId' is distinct from p_notebook_id
    or jsonb_typeof(p_manifest -> 'headSnapshotIds') is distinct from 'array'
    or jsonb_typeof(p_manifest -> 'prunedSnapshotIds') is distinct from 'array' then
    raise exception 'manifest is not a valid protocol v1 manifest' using errcode = '22023';
  end if;

  update public.sync_notebooks as n
  set manifest = p_manifest,
      manifest_version = n.manifest_version + 1,
      updated_at = now()
  where n.notebook_id = p_notebook_id
    and n.owner_id = v_owner_id
    and n.manifest_version = p_expected_manifest_version
  returning n.manifest, n.manifest_version
    into v_manifest, v_manifest_version;

  if found then
    return query select true, v_manifest, v_manifest_version;
    return;
  end if;

  select n.manifest, n.manifest_version
    into v_manifest, v_manifest_version
  from public.sync_notebooks as n
  where n.notebook_id = p_notebook_id
    and n.owner_id = v_owner_id;

  if not found then
    raise exception 'notebook is not owned by the authenticated user' using errcode = '42501';
  end if;

  return query select false, v_manifest, v_manifest_version;
end;
$$;

create or replace function public.delete_pruned_sync_snapshot(
  p_notebook_id text,
  p_snapshot_id text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_owner_id uuid := auth.uid();
begin
  if v_owner_id is null then
    raise exception 'authenticated user required' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.sync_notebooks as n
    where n.notebook_id = p_notebook_id
      and n.owner_id = v_owner_id
  ) then
    raise exception 'notebook is not owned by the authenticated user' using errcode = '42501';
  end if;

  delete from public.sync_snapshots as s
  using public.sync_notebooks as n
  where s.notebook_id = p_notebook_id
    and s.snapshot_id = p_snapshot_id
    and n.notebook_id = s.notebook_id
    and n.owner_id = v_owner_id
    and n.manifest -> 'prunedSnapshotIds' @> jsonb_build_array(p_snapshot_id)
    and not (n.manifest -> 'headSnapshotIds' @> jsonb_build_array(p_snapshot_id));

  if found then
    return true;
  end if;

  if not exists (
    select 1
    from public.sync_snapshots as s
    where s.notebook_id = p_notebook_id
      and s.snapshot_id = p_snapshot_id
  ) then
    return true;
  end if;

  raise exception 'snapshot is not marked pruned or is still a head' using errcode = 'P0001';
end;
$$;

revoke all on function public.initialize_sync_notebook(text, text, jsonb, jsonb) from public, anon;
revoke all on function public.create_sync_snapshot(text, text, jsonb) from public, anon;
revoke all on function public.compare_and_swap_sync_manifest(text, bigint, jsonb) from public, anon;
revoke all on function public.delete_pruned_sync_snapshot(text, text) from public, anon;

grant execute on function public.initialize_sync_notebook(text, text, jsonb, jsonb) to authenticated;
grant execute on function public.create_sync_snapshot(text, text, jsonb) to authenticated;
grant execute on function public.compare_and_swap_sync_manifest(text, bigint, jsonb) to authenticated;
grant execute on function public.delete_pruned_sync_snapshot(text, text) to authenticated;
